---
tasks:
  - name: Checks if server is already made
  

  - name: Check/create the /var/www directory


  - name: Create the HTML file in the /var/www directory
    

  - name: Copy default in /etc/nginx/sites-enabled/servername
    command: cp /etc/nginx/sites-available/default > /etc/nginx/sites-available/TestHost.com

  - name: Configure the file
    command: sudo vim /etc/nginx/sites-available/TestHost.com

  - name: Link the file to /etc/nginx/sites-enabled/servername


  - name: Restart nginx
    notify:
     name: restart nginx
