---
 - name: Check existing IPTables rules
   shell: iptables -L
   register: existingrules

 - name: Allow HTTP to connect through IPTables
   command: iptables -A INPUT -p tcp --sport 80 -j ACCEPT -m comment --comment "HTTP"
   when: existingrules.stdout.find("HTTP") == -1

 - name: Allow SSH to connect through IPTables
   command: iptables -A INPUT -p tcp --sport 22 -j ACCEPT -m comment --comment "SSH"
   notify:
     name: save iptables
     name: restart iptables
   when: existingrules.stdout.find("SSH") == -1